export const BASE_URL = 'http://localhost:8081/'
export const SOCKET_URL = 'ws://localhost:8081'
export const HOST_URL = BASE_URL + 'host'
export const SEARCH_URL = BASE_URL + 'search'
export const VALIDATE_ROOM_URL = BASE_URL + 'validate'
